export const KNOWN_TECHS = [
  "react", "react native", "vue", "angular", "svelte", "next.js", "nuxt", "gatsby", "remix",
  "typescript", "javascript", "html", "css", "scss", "sass", "tailwind", "bootstrap",
  "node.js", "express", "nestjs", "fastify", "deno", "bun",
  "python", "django", "flask", "fastapi", "celery",
  "java", "spring", "spring boot", "kotlin", "scala",
  "go", "golang", "rust", "ruby", "rails", "php", "laravel", "symfony", "yii",
  "c#", "csharp", ".net", "asp.net", "blazor",
  "c++", "c", "swift", "swiftui", "objective-c",
  "flutter", "dart", "xamarin", "expo",
  "sql", "postgresql", "mysql", "mariadb", "sqlite", "mssql",
  "mongodb", "redis", "elasticsearch", "cassandra", "dynamodb", "couchdb",
  "graphql", "rest api", "grpc", "websocket",
  "docker", "kubernetes", "terraform", "ansible", "jenkins", "ci/cd",
  "aws", "gcp", "azure", "heroku", "vercel", "netlify", "cloudflare",
  "linux", "nginx", "apache",
  "git", "github", "gitlab", "bitbucket",
  "jest", "mocha", "cypress", "playwright", "selenium", "pytest",
  "webpack", "vite", "esbuild", "rollup", "babel",
  "redux", "mobx", "zustand", "recoil", "jotai",
  "figma", "sketch", "adobe xd", "storybook",
  "tensorflow", "pytorch", "pandas", "numpy", "scikit-learn", "spark",
  "rabbitmq", "kafka", "nats",
  "supabase", "firebase", "strapi", "prisma", "drizzle",
  "elk stack", "grafana", "prometheus", "datadog", "helm",
  "jira", "confluence", "notion", "trello", "postman",
  "nosql", "microservices", "monorepo", "agile", "scrum",
  "posthog", "amplitude", "mixpanel",
  "shopify", "wordpress", "magento",
  "expo", "jupyter", "airflow", "a/b testing",
];
